// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"mini-accounting/config"
	"mini-accounting/internal/counting/delivery/presenter/http"
	"mini-accounting/internal/counting/domain/usecase"
	"mini-accounting/library"
	"mini-accounting/pkg/custom_validation"
	"mini-accounting/routes"
)

// Injectors from wire.go:

func InjectRoute(config2 config.Config, library2 library.Library) routes.Routes {
	engine := gin.New()
	countingUsecase := usecase.NewCountingUsecase(library2)
	customValidation := custom_validation.NewCustomValidation(config2, library2)
	countingHandler := http.NewCountingHandler(library2, countingUsecase, customValidation)
	routesRoutes := routes.New(engine, library2, countingHandler)
	return routesRoutes
}

// wire.go:

var ProviderSet = wire.NewSet(gin.New, custom_validation.NewCustomValidation, usecase.NewCountingUsecase, http.NewCountingHandler, routes.New)
